import Head from 'next/head'
import axios from 'axios';
import { useState, useEffect } from 'react';
import ContactList from '../src/components/contactList/ContactList'
import Header from '../src/components/header/Header';
export default function Home() {
  // const hola = [
  //   {
  //     name: "isaias",
  //     apellido: "ponce",
  //     email: "ieponce@espol.edu.ec"
  //   },

  //   {
  //     name: "madara",
  //     apellido: "rikudou",
  //     email: "chidori@espol.edu.ec"
  //   },


  // ]
  const [registros, setRegistros] = useState([]);
  const [reload, setReload] = useState(0);

  useEffect(() => {
    console.debug('Obteniendo datos de usuarios');
    setRegistros([])
    var URL = "https://f3s91itbb5.execute-api.us-east-2.amazonaws.com/dev/contacts"
    axios.get(URL)
    .then((response) => {
      if (response.status === 200) {
        console.log(response)
        setRegistros(JSON.parse(response.data.body));
      }
    });
  }, [reload]);


  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header  />

        <form>
          <div className='d-flex justify-content-center' style={{padding:"3%"}}>


       <ContactList list={registros}/>
          </div>

          <div className='d-flex justify-content-center'>

           
            <button type="submit" className=" btn btn-danger" onClick={(event) => {
              event.preventDefault();
              setReload(reload + 1);
            }}>
              Reload *
            </button>
          </div>

        </form>


      </main>
    </div>
  )
}
